### ISSUE TITLE
Half of IPA 

### ISSUE THREAD

**Issue by orac3000** [m-rtin/anki-ipa#11]
When I press the button of Anki IPA the add on shows only half of the IPA. If I write the word horse for example it shows only rs/.

**Comment by m-rtin** [comment]
Thanks for your feedback! [oxfordlearnersdictionaries.com](oxfordlearnersdictionaries.com) changed their code a bit. I adjusted Anki IPA, now it works again.

**Comment by orac3000** [comment]
Thank you 😍

Martin <notifications@github.com> schrieb am So., 9. Feb. 2020, 09:50:
