### ISSUE TITLE
Not work for french

### ISSUE THREAD

**Issue by lehung121** [m-rtin/anki-ipa#13]
Thanks for making this addon. It works very well with English. But when I try to make cards to learn french, something went wrong. It says "IPA not found". 

Someone have this error like me: 
![image](https://user-images.githubusercontent.com/4921871/74675849-192e9580-51e7-11ea-9bb7-72902641e7b3.png)

**Comment by m-rtin** [comment]
Thanks for your feedback! It should work now again.

**Comment by lehung121** [comment]
Wows, It works. Thank you
