### ISSUE TITLE
Error Anki IPA

### ISSUE THREAD

**Issue by noname123-456** [m-rtin/anki-ipa#16]
After install Anki IPA. When I restarted Anki, 
I encountered an error like the image below
![Capture](https://user-images.githubusercontent.com/64325120/80286200-37b78c80-8754-11ea-8739-e3c64934ad9b.PNG)
I am using Version 2.1.15 (442df9d6)
Window 10

**Comment by noname123-456** [comment]
> After install Anki IPA. When I restarted Anki,
> I encountered an error like the image below
> ![Capture](https://user-images.githubusercontent.com/64325120/80286200-37b78c80-8754-11ea-8739-e3c64934ad9b.PNG)

I am using Version 2.1.15 (442df9d6)
Window 10

**Comment by m-rtin** [comment]
Updating your Anki version should solve the problem.

**Comment by noname123-456** [comment]
Thank you very much !!

Vào Th 6, 1 thg 5, 2020 vào lúc 20:00 Martin <notifications@github.com>
đã viết:
