### ISSUE TITLE
How to change database.

### ISSUE THREAD

**Issue by Potapka** [m-rtin/anki-ipa#30]
This is completely new to me. Is there any possibility to change source database for Anki IPA? I found out the file CMU_dict.db, which is English IPA internal source? Other languages are probably parsing  from webpages. Actually I would prefer Merriam-Webster learner’s dictionary for us IPA. Is there a way?

**Comment by barolo** [comment]
I'm wondering about the same, I need British IPA.

**Comment by m-rtin** [comment]
The websites used for the IPA transcriptions can be seen in [this file](https://github.com/m-rtin/anki-ipa/blob/master/src/anki_ipa/parse_ipa_transcription.py). As you can see I currently use lexico for English.

**Comment by m-rtin** [comment]
@barolo British API is now available again: 
<img width="120" alt="image" src="https://user-images.githubusercontent.com/46455311/182034240-eee5ea14-d55d-4b9e-a6ce-4e58405a50ed.png">
