### ISSUE TITLE
Handling of heteronyms

### ISSUE THREAD

**Issue by Donterioo** [m-rtin/anki-ipa#36]
"A heteronym (also known as a heterophone) is a word that has a different pronunciation and meaning from another word but the same spelling"
For example, "close" can be pronounced in two ways. /ˈkloʊs/ as an adjective and /ˈkloʊz/ as a verb.

When adding the ipa pronunciation, there should at least be information that the word can be pronounced in several ways.

https://en.wikipedia.org/wiki/Heteronym_(linguistics)
https://www.oxfordlearnersdictionaries.com/definition/english/close1_1?q=close
https://www.oxfordlearnersdictionaries.com/definition/english/close2_1

**Comment by m-rtin** [comment]
I updated the addon. You now get a list of possible IPA transcriptions. Example for UK English:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/46455311/182033943-cbe13548-578d-41cf-b80f-0e0fe62234bd.png">
