### ISSUE TITLE
Unnecessary, incorrect alternative ipa transcriptions

### ISSUE THREAD

**Issue by Donterioo** [m-rtin/anki-ipa#38]
![Zrzut ekranu 2022-07-31 192215](https://user-images.githubusercontent.com/107410346/182038157-5117adf9-e235-4769-b2ea-2a05dfb1e40d.png)
![Zrzut ekranu 2022-07-31 192247](https://user-images.githubusercontent.com/107410346/182038158-21d4188a-279f-4731-b0fa-785032dab801.png)

**Comment by m-rtin** [comment]
I fixed it, please update the addon: 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/46455311/182046607-3c235c53-cea2-45e3-abde-a6c351ace37b.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/46455311/182046615-b41b976a-100d-4b0b-80f5-8309cf586012.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/46455311/182046624-16383bc5-637e-4ca3-84a3-9a921970c11c.png">

Sadly there is another bug for American English:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/46455311/182046643-5bdcf918-5610-4f8b-8aa0-e757b8e8e5fe.png">
I'll create another issue for it.
