### ISSUE TITLE
Weird british english ipa

### ISSUE THREAD

**Issue by Donterioo** [m-rtin/anki-ipa#40]
### ɝ doesn't exist in british english at all
![Zrzut ekranu 2022-08-02 142419](https://user-images.githubusercontent.com/107410346/182373856-40af7207-0101-4ad6-8124-75dbc818854c.png)

### I have no idea what it is -k̚ 
![Zrzut ekranu 2022-08-02 142630](https://user-images.githubusercontent.com/107410346/182374190-cc515996-0738-44a2-bef5-91ceebc2b0b0.png)

**Comment by m-rtin** [comment]
I fixed it, please update the addon. I assume you want British English: 
<img width="763" alt="image" src="https://user-images.githubusercontent.com/46455311/183249743-c10d8f56-54eb-4a7b-8960-c5f1bda48aac.png">

**Comment by m-rtin** [comment]
Regarding the other transcriptions, they are listed [here](https://en.wiktionary.org/wiki/back).

**Comment by Donterioo** [comment]
Thanks but now I realized that "out" is also wrong. It should be aʊt
https://en.m.wiktionary.org/wiki/out

**Comment by m-rtin** [comment]
Thanks! I created a [new issue](https://github.com/m-rtin/anki-ipa/issues/47#top).
