### ISSUE TITLE
unluckily it doesn't work with unluckily

### ISSUE THREAD

**Issue by tangor86** [m-rtin/anki-ipa#43]
I click a note icon but nothing happens if English word is "**unluckily**".

![image](https://user-images.githubusercontent.com/1785921/183246033-3fb35603-ef12-4366-9ca6-7a1b211b88c7.png)

**Comment by tangor86** [comment]
not sure if this can be fixed but would be good

**Comment by m-rtin** [comment]
I'm currently using Wiktionary for the English IPA transcriptions and it seems like they don't have one for "unlucky", see [here](https://en.wiktionary.org/wiki/unluckily).
