### ISSUE TITLE
[eng] Wrong output for English "out"

### ISSUE THREAD

**Issue by m-rtin** [m-rtin/anki-ipa#47]
**Describe the bug**
Wrong output for "out" when using "eng_b" or "eng_a".

**Screenshots**
<img width="756" alt="image" src="https://user-images.githubusercontent.com/46455311/183281611-a4a26861-c195-43dc-b2c5-0822966a8caa.png">

**Expected behavior**
Expected "aʊt", got "æɔt" (see https://en.m.wiktionary.org/wiki/out)

**Comment by LeidiFlores** [comment]
hello! Could you please assign this to me?

**Comment by m-rtin** [comment]
Sure! 👍  The code can be found [here](https://github.com/m-rtin/anki-ipa/blob/master/src/anki_ipa/parse_ipa_transcription.py#L45-L68). Feel free to clean up a bit if you want, right now it's a bit messy 😄 Make sure [these tests](https://github.com/m-rtin/anki-ipa/blob/master/src/anki_ipa/test_parse_ipa_transcription.py#L30-L43) are still running after you made changes.

**Comment by LeidiFlores** [comment]
hi @m-rtin ! is ready here https://github.com/m-rtin/anki-ipa/pull/59 for you review
