### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by corderop** [m-rtin/anki-ipa#55]
It would be helpful to have a keyboard shortcut that triggers the action. It will be a simple change, I can even make it.
I have checked the code and description and took a quick look at the code, and I don't see anything related to this, so I'm opening the issue. 

**Describe the solution you'd like**
The solution will be as simple as adding another parameter to the function that creates the button. 
Another optional feature could be to add this to the setting parser.

Let me know what you think @m-rtin. If you want to proceed, I would ask you to add the `hacktoberfest` tag to the repo if you don't mind!

**Comment by m-rtin** [comment]
That sounds like a great idea, I'd be happy if you implement it.

**Comment by corderop** [comment]
The `hacktoberfest` tag is at the repository level, but no problem 😄.

**Comment by m-rtin** [comment]
I added the tag on the repository level.
